services:
  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    Xiidea\EasyConfigBundle\Services\FormGroup\ConfigGroupInterface:
      tags: [ 'xiidea.easy_config.group' ]
  xiidea.easy_config.service_repository:
          class: Xiidea\EasyConfigBundle\Services\Repository\ConfigRepository
          arguments:
            - '@doctrine.orm.entity_manager'
            - '%xiidea.easy_config.config_class%'

  xiidea.easy_config.service_manager:
          class: Xiidea\EasyConfigBundle\Services\Manager\ConfigManager
          tags:
            - { name: config.processor }
          arguments:
            - '@xiidea.easy_config.service_repository'
            - '@form.factory'
            - '@security.token_storage'
            - '@security.authorization_checker'
            - !tagged xiidea.easy_config.group
  Xiidea\EasyConfigBundle\Services\Manager\ConfigManager: '@xiidea.easy_config.service_manager'

  Xiidea\EasyConfigBundle\Controller\ConfigApiController:
          tags:
            - { name: controller.service_arguments }

  Xiidea\EasyConfigBundle\Controller\ConfigurationController:
          tags:
            - { name: controller.service_arguments }
